### ISSUE TITLE
Missing info in documentation

### ISSUE THREAD

**Issue by janneman001** [geeekpi/picoBDK#1]
I miss information in documentation. From the led' s it is easy to find out they are connected to ground and so need a positive on the pin. From the buttons and the beeper also. 
Information about the display however is not clear which signal is connected to which pico (w) pins. i.e. what is "lcd sdi" for and "lcd rs" 
Also for the board to be used it would be nice to have an example video or so with how to wire button led and so on.
I hope this helps

**Comment by rprouse** [comment]
I totally agree that this needs more documentation. I managed to reverse engineer it using the MicroPython code examples,

| Pin | SPI |
| --- | --- |
| 6 | SCK/CLK |
| 7 | MOSI/SDI/TX |
| 4 | MISO/SDO |
| 13 | CS |
| 14 | RST |
| 15 | DC |

For C/C++ programming, I used this library, https://github.com/tvlad1234/pico-displayDrivs. It requires `LCD_setPins(15, 13, 14, 6, 7)`.

For `LCD_setRotation` assuming the top of the screen is the top of the board,

| Value | Result |
| -- | -- |
| 0 | Top is right side of board |
| 1 | Upside down |
| 2 | Top is left side of board |
| 3 | Rightside up |

**Comment by yoyojacky** [comment]
Please refer to wiki's instructions.
